"""drop local collection AI evaluation state

Revision ID: 20260806_0017
Revises: 20260805_0016
Create Date: 2026-08-06 17:15:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260806_0017"
down_revision = "20260805_0016"
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    configured = str(op.get_context().config.get_main_option("manzara_db_schema") or "").strip()
    value = configured or str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    value = value or "monocorpus"
    if not _SCHEMA_RE.fullmatch(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _qident(value: str) -> str:
    return f'"{value.replace(chr(34), chr(34) * 2)}"'


def _table(name: str) -> str:
    return f"{_qident(_schema())}.{_qident(name)}"


def upgrade() -> None:
    op.execute(f"DROP TABLE IF EXISTS {_table('library_collection_ai_evaluations')}")


def downgrade() -> None:
    op.execute(
        f"""
        CREATE TABLE {_table("library_collection_ai_evaluations")} (
            evaluation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            collection_id BIGINT NOT NULL,
            run_id BIGINT,
            model_name TEXT NOT NULL,
            prompt_version TEXT NOT NULL,
            input_hash TEXT NOT NULL,
            gold_verdict TEXT NOT NULL,
            verdict TEXT,
            confidence DOUBLE PRECISION,
            rationale TEXT,
            signals_json TEXT NOT NULL DEFAULT '[]',
            raw_response TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL,
            error_text TEXT,
            latency_ms BIGINT NOT NULL DEFAULT 0,
            prompt_tokens BIGINT NOT NULL DEFAULT 0,
            output_tokens BIGINT NOT NULL DEFAULT 0,
            started_at TEXT NOT NULL,
            completed_at TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            CONSTRAINT fk_library_collection_ai_evaluation_collection
                FOREIGN KEY (collection_id)
                REFERENCES {_table("library_collections")}(collection_id)
                ON DELETE CASCADE,
            CONSTRAINT uq_library_collection_ai_evaluation_input
                UNIQUE (collection_id, model_name, prompt_version, input_hash)
        )
        """
    )
    op.execute(
        f"""
        CREATE INDEX {_qident("idx_library_collection_ai_evaluations_run")}
        ON {_table("library_collection_ai_evaluations")} (run_id, model_name)
        """
    )
