"""add persistent task conveyor

Revision ID: 20260812_0024
Revises: 20260812_0023
Create Date: 2026-08-12 21:00:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260812_0024"
down_revision = "20260812_0023"
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    configured = str(
        op.get_context().config.get_main_option("manzara_db_schema") or ""
    ).strip()
    value = configured or str(
        os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus"
    ).strip()
    if not _SCHEMA_RE.fullmatch(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _table(name: str) -> str:
    return f'"{_schema()}"."{name}"'


def upgrade() -> None:
    op.execute(
        f"""
        ALTER TABLE {_table('task_definitions')}
        ADD COLUMN IF NOT EXISTS meaningful_result_json TEXT NOT NULL DEFAULT '{{}}'
        """
    )
    op.execute(
        f"""
        CREATE TABLE {_table('conveyor_definitions')} (
            conveyor_id TEXT PRIMARY KEY,
            revision BIGINT NOT NULL DEFAULT 0,
            stages_json TEXT NOT NULL DEFAULT '[]',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            CONSTRAINT ck_conveyor_singleton CHECK (conveyor_id = 'default'),
            CONSTRAINT ck_conveyor_revision CHECK (revision >= 0)
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE {_table('conveyor_runs')} (
            conveyor_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            definition_revision BIGINT NOT NULL,
            status TEXT NOT NULL,
            outcome TEXT,
            started_at TEXT NOT NULL,
            finished_at TEXT,
            stop_requested BIGINT NOT NULL DEFAULT 0,
            error_text TEXT,
            CONSTRAINT ck_conveyor_run_status CHECK (
                status IN ('starting', 'running', 'completed', 'failed', 'stopped')
            ),
            CONSTRAINT ck_conveyor_run_outcome CHECK (
                outcome IS NULL OR outcome IN ('completed', 'no_op')
            )
        )
        """
    )
    op.execute(
        f"""
        CREATE UNIQUE INDEX uq_conveyor_one_active_run
        ON {_table('conveyor_runs')} ((1))
        WHERE status IN ('starting', 'running')
        """
    )
    op.execute(
        f"""
        CREATE TABLE {_table('conveyor_run_items')} (
            conveyor_run_id BIGINT NOT NULL,
            item_id TEXT NOT NULL,
            stage_id TEXT NOT NULL,
            stage_order BIGINT NOT NULL,
            task_order BIGINT NOT NULL,
            task_id TEXT NOT NULL,
            status TEXT NOT NULL,
            task_run_id BIGINT,
            meaningful BIGINT,
            output_json TEXT NOT NULL DEFAULT '{{}}',
            error_text TEXT,
            started_at TEXT,
            finished_at TEXT,
            PRIMARY KEY (conveyor_run_id, item_id),
            FOREIGN KEY (conveyor_run_id)
                REFERENCES {_table('conveyor_runs')}(conveyor_run_id) ON DELETE CASCADE,
            FOREIGN KEY (task_run_id)
                REFERENCES {_table('runs')}(run_id) ON DELETE SET NULL,
            CONSTRAINT ck_conveyor_item_status CHECK (
                status IN (
                    'pending', 'starting', 'running', 'completed',
                    'failed', 'stopped', 'canceled'
                )
            ),
            CONSTRAINT ck_conveyor_item_meaningful CHECK (
                meaningful IS NULL OR meaningful IN (0, 1)
            ),
            CONSTRAINT ck_conveyor_item_order CHECK (
                stage_order >= 0 AND task_order >= 0
            )
        )
        """
    )
    op.execute(
        f"""
        CREATE INDEX idx_conveyor_run_items_stage
        ON {_table('conveyor_run_items')}
            (conveyor_run_id, stage_order, task_order)
        """
    )
    op.execute(
        f"""
        INSERT INTO {_table('conveyor_definitions')} (
            conveyor_id, revision, stages_json, created_at, updated_at
        ) VALUES (
            'default', 0, '[]', CURRENT_TIMESTAMP::text, CURRENT_TIMESTAMP::text
        )
        """
    )


def downgrade() -> None:
    op.execute(f"DROP TABLE IF EXISTS {_table('conveyor_run_items')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('conveyor_runs')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('conveyor_definitions')}")
    op.execute(
        f"""
        ALTER TABLE {_table('task_definitions')}
        DROP COLUMN IF EXISTS meaningful_result_json
        """
    )
