"""add library collections tables

Revision ID: 20260325_0004
Revises: 20260325_0003
Create Date: 2026-03-25 13:40:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260325_0004"
down_revision = "20260325_0003"
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    try:
        context = op.get_context()
        cfg = context.config if context is not None else None
        cfg_schema = str(cfg.get_main_option("manzara_db_schema") or "").strip() if cfg else ""
        if cfg_schema:
            value = cfg_schema
        else:
            value = str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    except Exception:
        value = str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    if not value:
        value = "monocorpus"
    if not _SCHEMA_RE.match(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _qident(value: str) -> str:
    return f'"{value.replace(chr(34), chr(34) * 2)}"'


def _table(name: str) -> str:
    return f"{_qident(_schema())}.{_qident(name)}"


def upgrade() -> None:
    schema = _schema()
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {_qident(schema)}")

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("library_collections")} (
            collection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_key TEXT NOT NULL UNIQUE,
            title TEXT NOT NULL,
            normalized_title TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'suggested',
            include_in_library BIGINT NOT NULL DEFAULT 1,
            confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
            item_count BIGINT NOT NULL DEFAULT 0,
            heuristics_json TEXT NOT NULL DEFAULT '{{}}',
            metadata_template_json TEXT NOT NULL DEFAULT '{{}}',
            notes TEXT,
            last_detected_at TEXT,
            applied_at TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_qident("idx_library_collections_status")}
        ON {_table("library_collections")} (status, include_in_library)
        """
    )
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_qident("idx_library_collections_title")}
        ON {_table("library_collections")} (normalized_title)
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("library_collection_items")} (
            collection_id BIGINT NOT NULL,
            md5 TEXT NOT NULL,
            item_title TEXT,
            item_hint TEXT,
            signal_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (collection_id, md5),
            UNIQUE (md5),
            FOREIGN KEY (collection_id) REFERENCES {_table("library_collections")}(collection_id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_qident("idx_library_collection_items_collection")}
        ON {_table("library_collection_items")} (collection_id)
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("library_collection_events")} (
            event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            action TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )


def downgrade() -> None:
    op.execute(f"DROP TABLE IF EXISTS {_table('library_collection_events')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('library_collection_items')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('library_collections')}")

