"""add shayan state tables

Revision ID: 20260326_0007
Revises: 20260325_0006
Create Date: 2026-03-26 14:20:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260326_0007"
down_revision = "20260325_0006"
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    try:
        context = op.get_context()
        cfg = context.config if context is not None else None
        cfg_schema = str(cfg.get_main_option("manzara_db_schema") or "").strip() if cfg else ""
        if cfg_schema:
            value = cfg_schema
        else:
            value = str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    except Exception:
        value = str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    if not value:
        value = "monocorpus"
    if not _SCHEMA_RE.match(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _qident(value: str) -> str:
    return f'"{value.replace(chr(34), chr(34) * 2)}"'


def _table(name: str) -> str:
    return f"{_qident(_schema())}.{_qident(name)}"


def upgrade() -> None:
    schema = _schema()
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {_qident(schema)}")

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("shayan_manifest_entries")} (
            entry_key TEXT PRIMARY KEY,
            payload_json TEXT NOT NULL,
            payload_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_qident("idx_shayan_manifest_entries_updated_at")}
        ON {_table("shayan_manifest_entries")} (updated_at DESC)
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("shayan_snapshots")} (
            snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT,
            source TEXT,
            generated_at TEXT,
            entries_count BIGINT NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (run_id) REFERENCES {_table("runs")}(run_id) ON DELETE SET NULL
        )
        """
    )
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_qident("idx_shayan_snapshots_generated_at")}
        ON {_table("shayan_snapshots")} (generated_at DESC, snapshot_id DESC)
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("shayan_snapshot_entries")} (
            snapshot_id BIGINT NOT NULL,
            entry_key TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            payload_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (snapshot_id, entry_key),
            FOREIGN KEY (snapshot_id) REFERENCES {_table("shayan_snapshots")}(snapshot_id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_qident("idx_shayan_snapshot_entries_snapshot")}
        ON {_table("shayan_snapshot_entries")} (snapshot_id, entry_key)
        """
    )


def downgrade() -> None:
    op.execute(f"DROP TABLE IF EXISTS {_table('shayan_snapshot_entries')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('shayan_snapshots')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('shayan_manifest_entries')}")
