"""drop retired Shayan state after standalone export

Revision ID: 20260827_0037
Revises: 20260827_0036
Create Date: 2026-08-27 13:00:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260827_0037"
down_revision = "20260827_0036"
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    configured = str(
        op.get_context().config.get_main_option("manzara_db_schema") or ""
    ).strip()
    value = configured or str(
        os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus"
    ).strip()
    if not _SCHEMA_RE.fullmatch(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _table(name: str) -> str:
    return f'"{_schema()}"."{name}"'


def _index(name: str) -> str:
    return f'"{_schema()}"."{name}"'


def upgrade() -> None:
    for name in (
        "shayan_run_changes",
        "shayan_snapshot_entries",
        "shayan_snapshots",
        "shayan_manifest_entries",
    ):
        op.execute(f"DROP TABLE IF EXISTS {_table(name)}")


def downgrade() -> None:
    op.execute(
        f"""
        CREATE TABLE {_table('shayan_manifest_entries')} (
            entry_key TEXT PRIMARY KEY,
            payload_json TEXT NOT NULL,
            payload_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            yadisk_status TEXT NOT NULL DEFAULT 'pending',
            yadisk_remote_path TEXT,
            yadisk_uploaded_payload_hash TEXT,
            yadisk_uploaded_at TEXT,
            yadisk_last_attempt_at TEXT,
            yadisk_last_error TEXT,
            webdav_status TEXT NOT NULL DEFAULT 'pending',
            webdav_remote_path TEXT,
            webdav_source_md5 TEXT,
            webdav_source_size BIGINT,
            webdav_target_etag TEXT,
            webdav_target_checksum TEXT,
            webdav_uploaded_payload_hash TEXT,
            webdav_uploaded_at TEXT,
            webdav_last_attempt_at TEXT,
            webdav_last_error TEXT
        )
        """
    )
    op.execute(
        f"CREATE INDEX {_index('idx_shayan_manifest_entries_updated_at')} "
        f"ON {_table('shayan_manifest_entries')} (updated_at DESC)"
    )
    op.execute(
        f"CREATE INDEX {_index('idx_shayan_manifest_entries_yadisk_status')} "
        f"ON {_table('shayan_manifest_entries')} (yadisk_status, updated_at DESC)"
    )
    op.execute(
        f"CREATE INDEX {_index('idx_shayan_manifest_entries_webdav_status')} "
        f"ON {_table('shayan_manifest_entries')} (webdav_status, updated_at DESC)"
    )

    op.execute(
        f"""
        CREATE TABLE {_table('shayan_snapshots')} (
            snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT,
            source TEXT,
            generated_at TEXT,
            entries_count BIGINT NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (run_id) REFERENCES {_table('runs')}(run_id) ON DELETE SET NULL
        )
        """
    )
    op.execute(
        f"CREATE INDEX {_index('idx_shayan_snapshots_generated_at')} "
        f"ON {_table('shayan_snapshots')} (generated_at DESC, snapshot_id DESC)"
    )

    op.execute(
        f"""
        CREATE TABLE {_table('shayan_snapshot_entries')} (
            snapshot_id BIGINT NOT NULL,
            entry_key TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            payload_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (snapshot_id, entry_key),
            FOREIGN KEY (snapshot_id) REFERENCES {_table('shayan_snapshots')}(snapshot_id)
                ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"CREATE INDEX {_index('idx_shayan_snapshot_entries_snapshot')} "
        f"ON {_table('shayan_snapshot_entries')} (snapshot_id, entry_key)"
    )

    op.execute(
        f"""
        CREATE TABLE {_table('shayan_run_changes')} (
            change_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL,
            change_type TEXT NOT NULL,
            entry_key TEXT NOT NULL,
            category TEXT,
            program TEXT,
            season BIGINT,
            episode BIGINT,
            title TEXT,
            old_payload_json TEXT NOT NULL DEFAULT '{{}}',
            new_payload_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL,
            FOREIGN KEY (run_id) REFERENCES {_table('runs')}(run_id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"CREATE INDEX {_index('idx_shayan_run_changes_run')} "
        f"ON {_table('shayan_run_changes')} (run_id, change_id)"
    )
    op.execute(
        f"CREATE INDEX {_index('idx_shayan_run_changes_type')} "
        f"ON {_table('shayan_run_changes')} (run_id, change_type, change_id)"
    )
