"""create manzara operational tables in target schema

Revision ID: 20260324_0001
Revises:
Create Date: 2026-03-24 16:40:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260324_0001"
down_revision = None
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    try:
        context = op.get_context()
        cfg = context.config if context is not None else None
        cfg_schema = str(cfg.get_main_option("manzara_db_schema") or "").strip() if cfg else ""
        if cfg_schema:
            value = cfg_schema
        else:
            value = str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    except Exception:
        value = str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    if not value:
        value = "monocorpus"
    if not _SCHEMA_RE.match(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _qident(value: str) -> str:
    return f'"{value.replace(chr(34), chr(34) * 2)}"'


def _table(name: str) -> str:
    return f"{_qident(_schema())}.{_qident(name)}"


def upgrade() -> None:
    schema = _schema()
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {_qident(schema)}")

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("task_definitions")} (
            task_id TEXT PRIMARY KEY,
            panel_id TEXT NOT NULL,
            title TEXT NOT NULL,
            task_type TEXT NOT NULL,
            icon_idle TEXT NOT NULL,
            icon_running TEXT NOT NULL,
            command_json TEXT NOT NULL,
            cwd TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("panel_definitions")} (
            panel_id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("runs")} (
            run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task_id TEXT NOT NULL,
            panel_id TEXT NOT NULL,
            status TEXT NOT NULL,
            stop_mode TEXT,
            pid BIGINT,
            started_at TEXT NOT NULL,
            finished_at TEXT,
            heartbeat_at TEXT,
            exit_code BIGINT,
            error_text TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (task_id) REFERENCES {_table("task_definitions")}(task_id)
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("run_logs")} (
            log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL,
            stream TEXT NOT NULL,
            line TEXT NOT NULL,
            ts TEXT NOT NULL,
            FOREIGN KEY (run_id) REFERENCES {_table("runs")}(run_id) ON DELETE CASCADE
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("events")} (
            event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type TEXT NOT NULL,
            task_id TEXT,
            run_id BIGINT,
            panel_id TEXT,
            ts TEXT NOT NULL,
            payload_json TEXT NOT NULL
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("workflows")} (
            workflow_id TEXT PRIMARY KEY,
            panel_id TEXT NOT NULL,
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            enabled BIGINT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("workflow_steps")} (
            workflow_id TEXT NOT NULL,
            step_order BIGINT NOT NULL,
            step_type TEXT NOT NULL,
            task_id TEXT,
            condition_json TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (workflow_id, step_order),
            FOREIGN KEY (workflow_id) REFERENCES {_table("workflows")}(workflow_id) ON DELETE CASCADE
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("workflow_schedules")} (
            schedule_id TEXT PRIMARY KEY,
            workflow_id TEXT NOT NULL,
            schedule_type TEXT NOT NULL,
            day_of_week BIGINT NOT NULL,
            time_of_day TEXT NOT NULL,
            timezone TEXT NOT NULL,
            interval_minutes BIGINT,
            enabled BIGINT NOT NULL,
            overlap_policy TEXT NOT NULL,
            catchup_policy TEXT NOT NULL,
            next_run_at TEXT,
            last_run_at TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (workflow_id) REFERENCES {_table("workflows")}(workflow_id) ON DELETE CASCADE
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("workflow_runs")} (
            workflow_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workflow_id TEXT NOT NULL,
            schedule_id TEXT,
            trigger_source TEXT NOT NULL,
            status TEXT NOT NULL,
            started_at TEXT NOT NULL,
            finished_at TEXT,
            context_json TEXT NOT NULL,
            error_text TEXT,
            FOREIGN KEY (workflow_id) REFERENCES {_table("workflows")}(workflow_id),
            FOREIGN KEY (schedule_id) REFERENCES {_table("workflow_schedules")}(schedule_id)
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("workflow_step_runs")} (
            step_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workflow_run_id BIGINT NOT NULL,
            step_order BIGINT NOT NULL,
            task_id TEXT,
            status TEXT NOT NULL,
            task_run_id BIGINT,
            started_at TEXT NOT NULL,
            finished_at TEXT,
            output_json TEXT NOT NULL,
            error_text TEXT,
            FOREIGN KEY (workflow_run_id) REFERENCES {_table("workflow_runs")}(workflow_run_id) ON DELETE CASCADE,
            FOREIGN KEY (task_run_id) REFERENCES {_table("runs")}(run_id)
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("normalization_canonicals")} (
            canonical_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type TEXT NOT NULL,
            display_name TEXT NOT NULL,
            normalized_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            merged_into_id BIGINT,
            notes TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("normalization_aliases")} (
            alias_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type TEXT NOT NULL,
            raw_name TEXT NOT NULL,
            normalized_name TEXT NOT NULL,
            script_label TEXT NOT NULL,
            docs_count BIGINT NOT NULL DEFAULT 0,
            mentions_count BIGINT NOT NULL DEFAULT 0,
            marker_count BIGINT NOT NULL DEFAULT 0,
            decision_status TEXT NOT NULL DEFAULT 'pending',
            canonical_id BIGINT,
            confidence DOUBLE PRECISION,
            source TEXT,
            reason TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(entity_type, raw_name),
            FOREIGN KEY (canonical_id) REFERENCES {_table("normalization_canonicals")}(canonical_id)
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("normalization_suggestions")} (
            suggestion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type TEXT NOT NULL,
            raw_name TEXT NOT NULL,
            normalized_name TEXT NOT NULL,
            target_canonical_id BIGINT,
            suggestion_kind TEXT NOT NULL,
            confidence DOUBLE PRECISION NOT NULL,
            confidence_band TEXT NOT NULL,
            model TEXT,
            rationale TEXT,
            status TEXT NOT NULL DEFAULT 'open',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (target_canonical_id) REFERENCES {_table("normalization_canonicals")}(canonical_id)
        )
        """
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("normalization_events")} (
            event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type TEXT NOT NULL,
            action TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            reverted BIGINT NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL
        )
        """
    )

    op.execute(f"CREATE INDEX IF NOT EXISTS idx_runs_task_status ON {_table('runs')}(task_id, status)")
    op.execute(f"CREATE INDEX IF NOT EXISTS idx_runs_status ON {_table('runs')}(status)")
    op.execute(f"CREATE INDEX IF NOT EXISTS idx_run_logs_run_id ON {_table('run_logs')}(run_id, log_id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS idx_events_event_id ON {_table('events')}(event_id)")
    op.execute(f"CREATE INDEX IF NOT EXISTS idx_panels_title ON {_table('panel_definitions')}(title)")
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_workflow_schedules_enabled_next "
        f"ON {_table('workflow_schedules')}(enabled, next_run_at)"
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_workflow_runs_status "
        f"ON {_table('workflow_runs')}(workflow_id, status)"
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_workflow_step_runs_workflow_run "
        f"ON {_table('workflow_step_runs')}(workflow_run_id, step_order)"
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_norm_canonicals_entity_status "
        f"ON {_table('normalization_canonicals')}(entity_type, status)"
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_norm_aliases_entity_status "
        f"ON {_table('normalization_aliases')}(entity_type, decision_status)"
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_norm_aliases_entity_raw "
        f"ON {_table('normalization_aliases')}(entity_type, raw_name)"
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_norm_suggestions_entity_status "
        f"ON {_table('normalization_suggestions')}(entity_type, status)"
    )
    op.execute(
        f"CREATE INDEX IF NOT EXISTS idx_norm_events_entity_created "
        f"ON {_table('normalization_events')}(entity_type, created_at DESC)"
    )


def downgrade() -> None:
    op.execute(f"DROP TABLE IF EXISTS {_table('normalization_events')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('normalization_suggestions')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('normalization_aliases')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('normalization_canonicals')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('workflow_step_runs')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('workflow_runs')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('workflow_schedules')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('workflow_steps')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('workflows')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('events')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('run_logs')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('runs')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('panel_definitions')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('task_definitions')}")
