"""remove the legacy workflow scheduler

Revision ID: 20260827_0036
Revises: 20260826_0035
Create Date: 2026-08-27 12:00:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260827_0036"
down_revision = "20260826_0035"
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    configured = str(
        op.get_context().config.get_main_option("manzara_db_schema") or ""
    ).strip()
    value = configured or str(
        os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus"
    ).strip()
    if not _SCHEMA_RE.fullmatch(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _table(name: str) -> str:
    return f'"{_schema()}"."{name}"'


def upgrade() -> None:
    op.execute(
        f"DELETE FROM {_table('events')} "
        "WHERE type LIKE 'schedule.%' OR type LIKE 'workflow.%'"
    )
    for name in (
        "workflow_step_runs",
        "workflow_runs",
        "workflow_schedules",
        "workflow_steps",
        "workflows",
    ):
        op.execute(f"DROP TABLE IF EXISTS {_table(name)}")


def downgrade() -> None:
    op.execute(
        f"""
        CREATE TABLE {_table('workflows')} (
            workflow_id TEXT PRIMARY KEY,
            panel_id TEXT NOT NULL,
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            enabled BIGINT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE {_table('workflow_steps')} (
            workflow_id TEXT NOT NULL,
            step_order BIGINT NOT NULL,
            step_type TEXT NOT NULL,
            task_id TEXT,
            condition_json TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (workflow_id, step_order),
            FOREIGN KEY (workflow_id) REFERENCES {_table('workflows')}(workflow_id)
                ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE {_table('workflow_schedules')} (
            schedule_id TEXT PRIMARY KEY,
            workflow_id TEXT NOT NULL,
            schedule_type TEXT NOT NULL,
            day_of_week BIGINT NOT NULL,
            time_of_day TEXT NOT NULL,
            timezone TEXT NOT NULL,
            interval_minutes BIGINT,
            enabled BIGINT NOT NULL,
            overlap_policy TEXT NOT NULL,
            catchup_policy TEXT NOT NULL,
            next_run_at TEXT,
            last_run_at TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (workflow_id) REFERENCES {_table('workflows')}(workflow_id)
                ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE {_table('workflow_runs')} (
            workflow_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workflow_id TEXT NOT NULL,
            schedule_id TEXT,
            trigger_source TEXT NOT NULL,
            status TEXT NOT NULL,
            started_at TEXT NOT NULL,
            finished_at TEXT,
            context_json TEXT NOT NULL,
            error_text TEXT,
            FOREIGN KEY (workflow_id) REFERENCES {_table('workflows')}(workflow_id),
            FOREIGN KEY (schedule_id)
                REFERENCES {_table('workflow_schedules')}(schedule_id)
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE {_table('workflow_step_runs')} (
            step_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workflow_run_id BIGINT NOT NULL,
            step_order BIGINT NOT NULL,
            task_id TEXT,
            status TEXT NOT NULL,
            task_run_id BIGINT,
            started_at TEXT NOT NULL,
            finished_at TEXT,
            output_json TEXT NOT NULL,
            error_text TEXT,
            FOREIGN KEY (workflow_run_id)
                REFERENCES {_table('workflow_runs')}(workflow_run_id) ON DELETE CASCADE,
            FOREIGN KEY (task_run_id) REFERENCES {_table('runs')}(run_id)
        )
        """
    )
