"""add guarded document cleanup queue and ISBN reviews

Revision ID: 20260808_0019
Revises: 20260806_0018
Create Date: 2026-08-08 12:00:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260808_0019"
down_revision = "20260806_0018"
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    configured = str(
        op.get_context().config.get_main_option("manzara_db_schema") or ""
    ).strip()
    value = configured or str(
        os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus"
    ).strip()
    if not _SCHEMA_RE.fullmatch(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _table(name: str) -> str:
    schema = _schema().replace('"', '""')
    table = name.replace('"', '""')
    return f'"{schema}"."{table}"'


def upgrade() -> None:
    queue = _table("document_cleanup_queue")
    reviews = _table("library_isbn_duplicate_reviews")
    op.execute(
        f"""
        CREATE TABLE {queue} (
            cleanup_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scope TEXT NOT NULL CHECK (scope IN ('document', 'duplicate_resource')),
            action TEXT NOT NULL CHECK (action IN ('move', 'delete')),
            reason TEXT NOT NULL,
            md5 TEXT NOT NULL,
            source_resource_id TEXT,
            source_path TEXT NOT NULL,
            target_path TEXT,
            status TEXT NOT NULL DEFAULT 'planned'
                CHECK (status IN ('planned', 'running', 'completed', 'failed')),
            phase TEXT NOT NULL DEFAULT 'planned',
            evidence_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
            attempts INTEGER NOT NULL DEFAULT 0,
            run_id BIGINT,
            last_error TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            completed_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        f"CREATE UNIQUE INDEX uq_document_cleanup_active_md5 ON {queue} (md5) "
        "WHERE scope = 'document' AND status IN ('planned', 'running', 'failed')"
    )
    op.execute(
        f"CREATE UNIQUE INDEX uq_document_cleanup_active_resource ON {queue} "
        "(source_resource_id) WHERE scope = 'duplicate_resource' "
        "AND source_resource_id IS NOT NULL "
        "AND status IN ('planned', 'running', 'failed')"
    )
    op.execute(
        f"CREATE INDEX idx_document_cleanup_status ON {queue} "
        "(status, cleanup_id)"
    )
    op.execute(
        f"""
        CREATE TABLE {reviews} (
            review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            isbn TEXT NOT NULL,
            candidate_hash TEXT NOT NULL,
            candidates_json JSONB NOT NULL,
            evidence_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
            keep_md5s_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            status TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'decided', 'superseded')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            decided_at TIMESTAMPTZ,
            UNIQUE (isbn, candidate_hash)
        )
        """
    )
    op.execute(
        f"CREATE INDEX idx_isbn_duplicate_reviews_status ON {reviews} "
        "(status, review_id)"
    )


def downgrade() -> None:
    op.execute(f"DROP TABLE IF EXISTS {_table('library_isbn_duplicate_reviews')}")
    op.execute(f"DROP TABLE IF EXISTS {_table('document_cleanup_queue')}")
