"""add shayan run changes table

Revision ID: 20260326_0008
Revises: 20260326_0007
Create Date: 2026-03-26 15:00:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260326_0008"
down_revision = "20260326_0007"
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    try:
        context = op.get_context()
        cfg = context.config if context is not None else None
        cfg_schema = str(cfg.get_main_option("manzara_db_schema") or "").strip() if cfg else ""
        if cfg_schema:
            value = cfg_schema
        else:
            value = str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    except Exception:
        value = str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    if not value:
        value = "monocorpus"
    if not _SCHEMA_RE.match(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _qident(value: str) -> str:
    return f'"{value.replace(chr(34), chr(34) * 2)}"'


def _table(name: str) -> str:
    return f"{_qident(_schema())}.{_qident(name)}"


def upgrade() -> None:
    schema = _schema()
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {_qident(schema)}")

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_table("shayan_run_changes")} (
            change_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL,
            change_type TEXT NOT NULL,
            entry_key TEXT NOT NULL,
            category TEXT,
            program TEXT,
            season BIGINT,
            episode BIGINT,
            title TEXT,
            old_payload_json TEXT NOT NULL DEFAULT '{{}}',
            new_payload_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL,
            FOREIGN KEY (run_id) REFERENCES {_table("runs")}(run_id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_qident("idx_shayan_run_changes_run")}
        ON {_table("shayan_run_changes")} (run_id, change_id)
        """
    )
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_qident("idx_shayan_run_changes_type")}
        ON {_table("shayan_run_changes")} (run_id, change_type, change_id)
        """
    )


def downgrade() -> None:
    op.execute(f"DROP TABLE IF EXISTS {_table('shayan_run_changes')}")
