"""redesign library collection detection around path-free proposals

Revision ID: 20260806_0018
Revises: 20260806_0017
Create Date: 2026-08-06 20:00:00
"""

from __future__ import annotations

import os
import re

from alembic import op


revision = "20260806_0018"
down_revision = "20260806_0017"
branch_labels = None
depends_on = None

_SCHEMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    configured = str(
        op.get_context().config.get_main_option("manzara_db_schema") or ""
    ).strip()
    value = (
        configured or str(os.environ.get("MANZARA_DB_SCHEMA") or "monocorpus").strip()
    )
    value = value or "monocorpus"
    if not _SCHEMA_RE.fullmatch(value):
        raise ValueError(f"Invalid schema name: {value!r}")
    return value


def _qident(value: str) -> str:
    return f'"{value.replace(chr(34), chr(34) * 2)}"'


def _table(name: str) -> str:
    return f"{_qident(_schema())}.{_qident(name)}"


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        f"""
        CREATE TABLE {_table("library_collection_document_features")} (
            md5 TEXT PRIMARY KEY,
            input_hash TEXT NOT NULL,
            eligible BOOLEAN NOT NULL,
            exclusion_reason TEXT NOT NULL DEFAULT '',
            title TEXT NOT NULL DEFAULT '',
            normalized_title TEXT NOT NULL DEFAULT '',
            title_core TEXT NOT NULL DEFAULT '',
            work_type TEXT NOT NULL DEFAULT '',
            publication_date TEXT NOT NULL DEFAULT '',
            publication_year INTEGER,
            issue_number TEXT NOT NULL DEFAULT '',
            publishers_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            authors_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            genres_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            description TEXT NOT NULL DEFAULT '',
            series_hints_json JSONB NOT NULL DEFAULT '[]'::jsonb,
            has_issue_marker BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    op.execute(
        f"CREATE INDEX idx_library_collection_features_eligible_core "
        f"ON {_table('library_collection_document_features')} (eligible, title_core)"
    )
    op.execute(
        f"CREATE INDEX idx_library_collection_features_core_trgm "
        f"ON {_table('library_collection_document_features')} USING GIN (title_core gin_trgm_ops)"
    )

    op.execute(
        f"""
        CREATE TABLE {_table("library_collection_signatures")} (
            signature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            collection_id BIGINT NOT NULL,
            signature_type TEXT NOT NULL,
            normalized_value TEXT NOT NULL,
            provenance TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            CONSTRAINT fk_library_collection_signature_collection
                FOREIGN KEY (collection_id) REFERENCES {_table("library_collections")}(collection_id)
                ON DELETE CASCADE,
            CONSTRAINT uq_library_collection_signature
                UNIQUE (collection_id, signature_type, normalized_value)
        )
        """
    )
    op.execute(
        f"CREATE INDEX idx_library_collection_signatures_value_trgm "
        f"ON {_table('library_collection_signatures')} USING GIN (normalized_value gin_trgm_ops)"
    )

    op.execute(
        f"""
        CREATE TABLE {_table("library_collection_proposals")} (
            proposal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            proposal_key TEXT NOT NULL UNIQUE,
            proposal_type TEXT NOT NULL,
            target_collection_id BIGINT,
            proposed_title TEXT NOT NULL,
            normalized_title TEXT NOT NULL,
            status TEXT NOT NULL,
            detector_version TEXT NOT NULL,
            deterministic_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
            evidence_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
            gemini_collection_verdict BOOLEAN,
            gemini_canonical_name TEXT,
            gemini_confidence DOUBLE PRECISION,
            gemini_rationale TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            reviewed_at TEXT,
            superseded_at TEXT,
            CONSTRAINT fk_library_collection_proposal_target
                FOREIGN KEY (target_collection_id) REFERENCES {_table("library_collections")}(collection_id)
                ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"CREATE INDEX idx_library_collection_proposals_queue "
        f"ON {_table('library_collection_proposals')} (status, updated_at, proposal_id)"
    )

    op.execute(
        f"""
        CREATE TABLE {_table("library_collection_proposal_items")} (
            proposal_id BIGINT NOT NULL,
            md5 TEXT NOT NULL,
            input_hash TEXT NOT NULL,
            deterministic_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
            evidence_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
            gemini_verdict TEXT,
            gemini_confidence DOUBLE PRECISION,
            gemini_rationale TEXT,
            gemini_model TEXT,
            prompt_version TEXT,
            validated_at TEXT,
            decision TEXT,
            PRIMARY KEY (proposal_id, md5),
            CONSTRAINT fk_library_collection_proposal_item_proposal
                FOREIGN KEY (proposal_id) REFERENCES {_table("library_collection_proposals")}(proposal_id)
                ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"CREATE INDEX idx_library_collection_proposal_items_md5 "
        f"ON {_table('library_collection_proposal_items')} (md5, proposal_id)"
    )

    op.execute(
        f"""
        CREATE TABLE {_table("library_collection_validation_attempts")} (
            attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            proposal_id BIGINT NOT NULL,
            run_id BIGINT,
            model_name TEXT NOT NULL,
            prompt_version TEXT NOT NULL,
            input_hash TEXT NOT NULL,
            requested_md5_json JSONB NOT NULL,
            batch_size INTEGER NOT NULL,
            status TEXT NOT NULL,
            response_json JSONB,
            error_text TEXT,
            latency_ms BIGINT NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            completed_at TEXT NOT NULL,
            CONSTRAINT fk_library_collection_validation_proposal
                FOREIGN KEY (proposal_id) REFERENCES {_table("library_collection_proposals")}(proposal_id)
                ON DELETE CASCADE
        )
        """
    )
    op.execute(
        f"CREATE INDEX idx_library_collection_validation_attempts_recent "
        f"ON {_table('library_collection_validation_attempts')} (model_name, attempt_id DESC)"
    )

    # Preserve rejected human decisions as path-free, immutable proposal history.
    op.execute(
        f"""
        INSERT INTO {_table("library_collection_proposals")} (
            proposal_key, proposal_type, target_collection_id, proposed_title,
            normalized_title, status, detector_version, deterministic_score,
            evidence_json, created_at, updated_at, reviewed_at
        )
        SELECT
            'legacy-rejected:' || md5(c.source_key || ':' || c.collection_id::text),
            'new_collection', NULL, c.title, c.normalized_title, 'rejected',
            'legacy-path-v1', c.confidence,
            jsonb_build_object('migrated_from_legacy', true),
            c.created_at, c.updated_at, c.updated_at
        FROM {_table("library_collections")} c
        WHERE c.status = 'rejected'
        """
    )
    op.execute(
        f"""
        INSERT INTO {_table("library_collection_proposal_items")} (
            proposal_id, md5, input_hash, deterministic_score, evidence_json, decision
        )
        SELECT p.proposal_id, i.md5, md5(i.md5), p.deterministic_score,
               jsonb_build_object('migrated_from_legacy', true), 'rejected'
        FROM {_table("library_collections")} c
        JOIN {_table("library_collection_proposals")} p
          ON p.proposal_key = 'legacy-rejected:' || md5(c.source_key || ':' || c.collection_id::text)
        JOIN {_table("library_collection_items")} i ON i.collection_id = c.collection_id
        WHERE c.status = 'rejected'
        """
    )

    # Seed durable canonical signatures before removing legacy source keys.
    op.execute(
        f"""
        INSERT INTO {_table("library_collection_signatures")} (
            collection_id, signature_type, normalized_value, provenance, created_at, updated_at
        )
        SELECT collection_id, 'canonical_title', normalized_title, 'migration', created_at, updated_at
        FROM {_table("library_collections")}
        WHERE status = 'approved' AND normalized_title <> ''
        ON CONFLICT DO NOTHING
        """
    )
    op.execute(
        f"DELETE FROM {_table('library_collection_items')} i USING {_table('library_collections')} c "
        f"WHERE i.collection_id = c.collection_id AND c.status <> 'approved'"
    )
    op.execute(
        f"DELETE FROM {_table('library_collections')} WHERE status <> 'approved'"
    )
    op.execute(f"DROP TABLE {_table('library_collection_source_aliases')}")
    op.execute(
        f"ALTER TABLE {_table('library_collection_items')} DROP COLUMN item_hint"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collection_items')} DROP COLUMN signal_json"
    )
    for column in (
        "source_key",
        "status",
        "confidence",
        "item_count",
        "heuristics_json",
        "last_detected_at",
    ):
        op.execute(f"ALTER TABLE {_table('library_collections')} DROP COLUMN {column}")


def downgrade() -> None:
    op.execute(
        f"ALTER TABLE {_table('library_collections')} ADD COLUMN source_key TEXT"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collections')} ADD COLUMN status TEXT NOT NULL DEFAULT 'approved'"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collections')} ADD COLUMN confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collections')} ADD COLUMN item_count BIGINT NOT NULL DEFAULT 0"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collections')} ADD COLUMN heuristics_json TEXT NOT NULL DEFAULT '{{}}'"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collections')} ADD COLUMN last_detected_at TEXT"
    )
    op.execute(
        f"UPDATE {_table('library_collections')} SET source_key = 'canonical|' || collection_id::text, "
        f"item_count = (SELECT COUNT(*) FROM {_table('library_collection_items')} i "
        f"WHERE i.collection_id = {_table('library_collections')}.collection_id)"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collections')} ALTER COLUMN source_key SET NOT NULL"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collections')} ADD CONSTRAINT uq_library_collections_source_key UNIQUE (source_key)"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collection_items')} ADD COLUMN item_hint TEXT"
    )
    op.execute(
        f"ALTER TABLE {_table('library_collection_items')} ADD COLUMN signal_json TEXT NOT NULL DEFAULT '{{}}'"
    )
    op.execute(
        f"""
        CREATE TABLE {_table("library_collection_source_aliases")} (
            source_key TEXT PRIMARY KEY,
            collection_id BIGINT NOT NULL REFERENCES {_table("library_collections")}(collection_id) ON DELETE CASCADE,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    for table_name in (
        "library_collection_validation_attempts",
        "library_collection_proposal_items",
        "library_collection_proposals",
        "library_collection_signatures",
        "library_collection_document_features",
    ):
        op.execute(f"DROP TABLE IF EXISTS {_table(table_name)} CASCADE")
