"""Shared task run states."""

from __future__ import annotations


TASK_RUN_STATUS_STARTING = "starting"
TASK_RUN_STATUS_RUNNING = "running"
TASK_RUN_STATUS_STOPPING_GRACEFUL = "stopping_graceful"
TASK_RUN_STATUS_STOPPED = "stopped"
TASK_RUN_STATUS_COMPLETED = "completed"
TASK_RUN_STATUS_FAILED = "failed"

TASK_RUN_ACTIVE_STATUSES = (
    TASK_RUN_STATUS_STARTING,
    TASK_RUN_STATUS_RUNNING,
    TASK_RUN_STATUS_STOPPING_GRACEFUL,
)
